# sql-ci.yml
name: SQL CI

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Workflow Running
        run: echo "SQL CI is working successfully!"